@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
ContainerDb(auth_db, "Database", "Postgre SQL", "Пользователи, роли и т.п.")
Rel(auth, auth_db, "Чтение / Запись", "Sync, TCP")
@enduml