openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Delivery
  description: Доставка товаров
paths:
  /api/v1/orders/{orderId}/complete:
    post:
      summary: Завершить выполнение заказа
      description: Позволяет завершить выполнение заказа
      operationId: CompleteOrder
      parameters:
        - name: orderId
          in: path
          description: Идентификатор заказа
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Успешный ответ
        default:
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/orders/{orderId}/cancel:
    post:
      summary: Отменить заказ
      description: Позволяет отменить заказ
      operationId: CancelOrder
      parameters:
        - name: orderId
          in: path
          description: Идентификатор заказа
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Успешный ответ
        default:
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/orders/{orderId}:
    get:
      summary: Получить информацию о заказе
      description: Позволяет получить состав заказа
      operationId: GetBasketItems
      parameters:
        - name: orderId
          in: path
          description: Идентификатор заказа
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        default:
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
 
components:
  schemas:
    Address:
      allOf:
        - required:
          - country
          - city
          - street
          - house
          - apartment
          properties:
            country:
              type: string
              description: Страна
            city:
              type: string
              description: Город
            street:
              type: string
              description: Улица
            house:
              type: string
              description: Дом 
            apartment:
              type: string
              description: Квартира
    BankCard:
      allOf:
        - required:
            - number
            - month
            - year
            - cardholderName
            - cvc
          properties:
            number:
              type: string
              description: Номер
            month:
              type: integer
              format: int32
              description: Месяц
            year:
              type: integer
              format: int32
              description: Год
            cardholderName:
              type: string
              description: Имя держателя
            cvc:
              type: string
              description: Cvc код
    DeliveryPeriod:
      type: string
      enum:
        - morning
        - midday
        - evening
        - night
    Item:
      allOf:
        - required:
            - goodId
            - quantity            
          properties:
            goodId:
              type: string
              format: uuid
              description: Идентификатор товара
            quantity:
              type: integer
              format: int32
              description: Количество            
    Good:
      allOf:
        - required:
          - id
          properties:
            id:
              type: string
              format: uuid
              description: Идентификатор
            title:
              type: string
              description: Название
            description:
              type: string
              description: Описание    
    Order:
      allOf:
        - required:
          - id
          - address
          properties:
            id:
              type: string
              format: uuid
              description: Идентификатор
            address:
              type: string
              format: uuid
              description: Идентификатор

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Код ошибки
        message:
          type: string
          description: Текст ошибки