openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Basket
  description: Корзина товаров
paths:
  /api/v1/baskets/{id}/address/add:
    post:
      summary: Добавить адрес доставки
      description: Позволяет добавить адрес доставки
      operationId: AddAddress
      parameters:
        - name: id
          in: path
          description: Идентификатор корзины
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Адрес
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
      responses:
        '200':
          description: Успешный ответ
        default:
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/baskets/{id}/bank-card/add:
    post:
      summary: Добавить банковскую карту
      description: Позволяет добавить средство оплаты
      operationId: AddBankCard
      parameters:
        - name: id
          in: path
          description: Идентификатор корзины
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Банковская карта
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BankCard'
      responses:
        '200':
          description: Успешный ответ
        default:
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/baskets/{id}/delivery-period/add:
    post:
      summary: Добавить период доставки
      description: Позволяет период доставки
      operationId: AddDeliveryPeriod
      parameters:
        - name: id
          in: path
          description: Идентификатор корзины
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Период доставки
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeliveryPeriod'
      responses:
        '200':
          description: Успешный ответ
        default:
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'              
  /api/v1/baskets/{basketId}/items/change:
    post:
      summary: Изменить позицию
      description: Позволяет добавить/удалить/изменить позицию
      operationId: ChangeItems
      parameters:
        - name: basketId
          in: path
          description: Идентификатор корзины
          required: true
          schema:
            type: string
            format: uuid          
      requestBody:
        description: Позиция
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '200':
          description: Успешный ответ
        default:
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/baskets/{basketId}/items:
    get:
      summary: Получить состав корзины
      description: Позволяет получить состав корзины
      operationId: GetBasketItems
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
        default:
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
 
components:
  schemas:
    Address:
      allOf:
        - required:
          - country
          - city
          - street
          - house
          - apartment
          properties:
            country:
              type: string
              description: Страна
            city:
              type: string
              description: Город
            street:
              type: string
              description: Улица
            house:
              type: string
              description: Дом 
            apartment:
              type: string
              description: Квартира
    BankCard:
      allOf:
        - required:
            - number
            - month
            - year
            - cardholderName
            - cvc
          properties:
            number:
              type: string
              description: Номер
            month:
              type: integer
              format: int32
              description: Месяц
            year:
              type: integer
              format: int32
              description: Год
            cardholderName:
              type: string
              description: Имя держателя
            cvc:
              type: string
              description: Cvc код
    DeliveryPeriod:
      type: string
      enum:
        - morning
        - midday
        - evening
        - night
    Item:
      allOf:
        - required:
            - goodId
            - quantity            
          properties:
            goodId:
              type: string
              format: uuid
              description: Идентификатор товара
            quantity:
              type: integer
              format: int32
              description: Количество            
    Good:
      allOf:
        - required:
          - id
          properties:
            id:
              type: string
              format: uuid
              description: Идентификатор
            title:
              type: string
              description: Название
            description:
              type: string
              description: Описание    
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Код ошибки
        message:
          type: string
          description: Текст ошибки